docs/main/ios/deploying-to-app-store.md, versioned_docs/version-v3/main/ios/deploying-to-app-store.md
https://capacitorjs.com/docs/ios/deploying-to-app-store is broken because of a typo on the slug
=> docs(ios): Fix link to deploying to app store

CONTRIBUTING.md, README.md
The contributing file refers to Ionic and links ionic repositories.
Replaced Ionic with Capacitor and linked Capacitor repositories where relevant.
Also removed the translation section as Capacitor site is not translated at the moment.
=> docs(contributing): Update to Capacitor

versioned_docs/version-v3/main/updating/3-0.md, versioned_docs/version-v3/main/web/index.md, versioned_docs/version-v3/plugins/creating-plugins/android-guide.md, versioned_docs/version-v3/plugins/creating-plugins/ios-guide.md
There are a few urls with a double v3 on in on the v3 versioned docs that breaks the links they point to.
This PR removes one of the v3 to fix the links
=> fix: remove double v3 on versioned links

docs/main/updating/4-0.md
Some users didn't do this step on the Capacitor 2 to 3 upgrade and now will fail to build if init method is still present, so add a step for removing it on the Capacitor 4 upgrade guide.
=> docs: Remove init method on android upgrade

docs/main/basics/workflow.md
The build command for "Create React App" or "Vite" should be `npm run build` instead of `npm build`.
=> docs: fix typo

docs/main/getting-started/installation.md
You can ~~using~~ use the @capacitor/create-app package to create a Capacitor application from scratch
=> fix: typo in installing capacitor

docs/main/updating/3-0.md
The 2.0-3.0 upgrade guide page currently instructs users to install the @latest tag of a few cap packages, which will pull 4.x now. Updated references to pull @latest-3 instead
=> fix: use @latest-3 instead of @latest on capacitor 3 upgrade guide

docs/main/guides/deep-links.md
The previous link was broken, the one added is the only other in the official docs in the category
=> fix: Update broken iOS universal links url on deep-links guide

docs/plugins/creating-plugins/overview.md
Adding the `@latest` tag to the plugin generator instructions. This will help ensure devs always start with the latest version.
=> docs(creating-plugins): mark "@latest"

docs/cli/commands/build.md, docs/cli/commands/copy.md
Document based on the PRs: 
- [feat(cli): add build command for android](https://github.com/ionic-team/capacitor/pull/5891)
- [feat(cli): add build command for ios](https://github.com/ionic-team/capacitor/pull/5925/files)
- [feat(cli): add inline option to copy command](https://github.com/ionic-team/capacitor/pull/5901)
=> doc(cli): add page for the cap build command and --inline option for cap copy

docs/main/getting-started/environment-setup.md
adding the word "can" here makes it read more naturally
=> fix: typo in environment-setup.md 

docs/main/deployment/desktop-app.md
This commit fixes the dead link to the Electron first app tutorial.
=> docs: fix Electron tutorial link

docs/main/getting-started/faqs.md
We no longer sell this, so we should not promote it as something we offer. We can always add it back later if we do start supporting it again at some point.
https://ionicteam.slack.com/archives/CERCH966L/p1676907128651719?thread_ts=1676906317.057429&cid=CERCH966L
=> doc(faqs): remove Windows as an official platform

docs/main/getting-started/installation.md
=> docs: fix typo on installation page

versioned_docs/version-v4/main/getting-started/environment-setup.md
> "If you do not want to install Homebrew, alternative, but not recommended, instructions can be found below." 
Seemed like broken english. It is possible that there is some reason it's phrased this way that I'm unaware of. But it annoyed me so I'm putting in a pull request.
=> docs: fixed some broken grammer. 

docs/plugins/community.md, versioned_docs/version-v4/plugins/community.md
As already discussed with Michael, I would be more than happy if Capawesome gets a mention in the official Capacitor Docs. 
This is just a suggestion from me.
Let me know if there is anything you would like me to change.
=> docs(plugins): add `Capawesome` section

docs/main/getting-started/environment-setup.md, docs/main/updating/5-0.md, versioned_docs/version-v4/main/getting-started/environment-setup.md
Update Capacitor 4 requirements as node 12 is still supported there.
Update Capacitor 5 requirements to indicate that node 16 is required
Update Capacitor 5 migrate guide to indicate that node 16 is required
=> docs: Update nodeJS information

docs/main/updating/plugins/5-0.md
Separated the migration steps from the breaking changes in code
Added information about `@capacitor/plugin-migration-v4-to-v5`
Added missing updates such as npm package updates and java 17
=> docs: Add information about plugin migration tool

docs/main/updating/5-0.md
The guide was missing the new required camera permission `<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>`
Also we didn't document the default values of the plugin variables, so I've added them (v4 guide included that information)
=> docs: add missing Capacitor 5 plugin info

vercel.json
@jaredcbaum not sure if this should go here or in capacitor-site repository, but we need to redirect the now non existent "docs/next/whatever" urls to "docs/whatever".
This change seems to work
=> chore: redirect next to root

docs/apis/action-sheet.md, docs/apis/browser.md, docs/apis/camera.md, docs/apis/geolocation.md, docs/apis/google-maps.md, docs/apis/push-notifications.md, docs/apis/splash-screen.md, scripts/api-v4.mjs, scripts/api.mjs
update plugin generators to use latest tag on capacitor 5 and latest-4 tag on capacitor 4 (note, we need to mark all Capacitor 4 packages as latest-4)
=> docs: Get capacitor 5 final plugin docs

docusaurus.config.js
This adds syntax highlighting to pages like this:
https://capacitorjs.com/docs/v2/plugins/android
https://capacitorjs.com/docs/plugins/android
=> fix(config): Add java and kotlin to Prism languages

docs/main/updating/4-0.md, docs/main/updating/plugins/5-0.md, versioned_docs/version-v4/main/updating/4-0.md
Close #188
This PR replace the no-break space (U+00A0) with normal whitespace (U+0020).
This change will ensure that the markdown parser can parse the text properly, and thus avoids some unexpected results.
=> chore: replace no-break space with normal whitespace

docs/cli/commands/build.md
The `--flavor` option is missing in the docs
=> add `--flavor` option to `npx cap build` cmd

docs/cli/commands/copy.md, docs/cli/commands/sync.md, docs/cli/commands/update.md
Currently the links to the CLI Hooks documentation are broken.
I fixed the links to get them reaching the docs one level up.
=> Fix broken links to CLI Hooks documentation

docs/plugins/official.md
Add the Background Runner and Watch plugins to the [Official plugins](https://capacitorjs.com/docs/apis) list.
=> Add Background Runner and Watch plugins to "Official plugins" list

docs/main/web/pwa-elements.md
When the docs were migrated some changes made [here](https://github.com/ionic-team/capacitor-site/pull/285) were missed (titles, shadow dom link, vue example, etc.), so bringing them back.
Also changed the docs around the defineCustomElements since it should be called before the app is rendered/registered/created.
=> docs(pwa-elements): Change information around defineCustomElements call

sidebars.js, versioned_sidebars/version-v3-sidebars.json, versioned_sidebars/version-v4-sidebars.json
**Problem:**
In the the Plugin Tutorial:
After *Using the Plugin API* the text ends with *[...] next step: the web implementation.*
After *Implementing for Web/PWA* the text ends with *[...]  the next step: code abstraction patterns.*
**Solution:**
Fix order in sidebar for the Plugin Tutorial for versions:
- V3, V4, V5
V2 does not have the tutorial.
=> Fix order in sidebar for the Plugin Tutorial

versioned_docs/version-v5/main/basics/workflow.md
Fix a typo, and replace the appflow link with the current live one
=> docs(workflow): typo and appflow link

docs/main/guides/splash-screens-and-icons.md
The @capacitor/assets lib recommends to use /assets instead /resources folder.
=> Update splash-screens-and-icons.md to right path

docs/main/reference/config.md
updates the config definition for androidScheme to include information about the change in Android Webview 117
=> docs: update config for androidScheme

docs/apis/splash-screen.md
The setting for `backgroundColor` is only works for Android 11 and below. This documentation is important for anyone who wants to use a background color for their splash screen.
=> doc(splashscreen): describe how to set background color on Android 12+

vercel.json
This reverts commit 9bbc99cdee20e18bb602f299eff309ef70ef291b.
v6 is now being shown under "next" so we need to revert this change. Next time the redirects should be marked as temporary.
=> Revert next directory redirects

versioned_docs/version-v5/main/reference/config.md
add missing information from declarations file for Capacitor 5
=> chore: Update Capacitor 5 config file docs

docs/main/guides/environment-specific-configurations.md, versioned_docs/version-v4/main/guides/environment-specific-configurations.md, versioned_docs/version-v5/main/guides/environment-specific-configurations.md
`flavorDimensions` with string is deprecated and now it takes an array instead of a string.
Not sure in which version it changed, so I've only updated capacitor 5 and 6 docs since that's where I'm seeing the warning, but have not tried in older versions.
=> docs: update flavorDimensions syntax

versioned_docs/version-v5/main/getting-started/environment-setup.md
I recommend going with either "macOS packages" (as in this branch) or "macOS" alone.
=> docs: fix typo in environment setup

versioned_docs/version-v5/plugins/creating-plugins/method-types.md
Fix small typo in code example.
=> docs: fix typo in method-types.md

docs/main/getting-started/environment-setup.md, versioned_docs/version-v4/main/getting-started/environment-setup.md, versioned_docs/version-v5/main/getting-started/environment-setup.md
The image is showing SDK 28 and 29 installed, not 30 and 31
=> docs: Update texts of installed SDKs

docs/main/updating/plugins/5-0.md
There is no `latest-5` of `@capacitor/plugin-migration-v4-to-v5`, the new package is called `@capacitor/plugin-migration-v5-to-v6`, so latest `@capacitor/plugin-migration-v4-to-v5` is still `@capacitor/plugin-migration-v4-to-v5`
=> docs: use latest plugin-migration-v4-to-v5

docs/apis/device.md, docs/apis/filesystem.md, docs/apis/preferences.md, docs/apis/watch.md, scripts/api.mjs
Use `latest` instead of `next` in the plugin generator script, except for google maps as `latest` there is still the v5 as it was not released.
Regenerate the files so they include the privacy manifest information.
=> chore: Update plugin docs generator for Capacitor 6

docs/main/updating/6-0.md
`next` links no longer work, use relative links to the .md files
=> chore: use relative links in update guide

docs/main/ios/spm.md
Remove references to "beta".
Install packages without "next"
Remove the section about editing the package.json since we don't want to use next now but latest (default)
=> docs: Update SPM docs

docs/main/ios/custom-code.md, docs/main/ios/viewcontroller.md
The Objective-C class is no longer needed.
A custom ViewController is needed and call to `registerPluginInstance`.
closes https://github.com/ionic-team/capacitor-docs/issues/275
=> docs: Update custom code information for Capacitor 6

docs/main/updating/6-0.md
There have been several issues and complains from people using custom plugins that no longer work in Capacitor 6 since the automatic plugin registration was removed.
I updated the custom code guide in a previous guide, but it should be mentioned in the upgrade guide too.
=> docs: Add register plugin section on migrate guide

docs/plugins/creating-plugins/development-workflow.md, docs/plugins/creating-plugins/ios-guide.md
There have been several reports of the plugin guide being out of date or incorrect because the plugin generator now creates SPM ready plugins, but the docs still refer to the `.m` classes and `.xcworkspace` file.
This PR updates the guide to only refer `.swift` files and the new SPM structure of the plugins.
Also adds information about the implementation class since it's been around for a few years already and the guide doesn't mention it and can be confusing since we talk about a single file but there are two.
related: https://github.com/ionic-team/create-capacitor-plugin/issues/103
=> docs: Update creating plugins guide for new structure

docs/plugins/creating-plugins/configuration-values.md, versioned_docs/version-v5/plugins/creating-plugins/configuration-values.md
closes https://github.com/ionic-team/capacitor-docs/issues/270
=> docs: Replace deprecated getConfigValue usages

docs/main/ios/privacy-manifest.md, docs/main/vs-code-ext/recommendations.md, versioned_docs/version-v4/main/ios/privacy-manifest.md, versioned_docs/version-v4/main/vs-code-ext/recommendations.md, versioned_docs/version-v5/main/ios/privacy-manifest.md, versioned_docs/version-v5/main/vs-code-ext/recommendations.md
The links to the VS Code extension issues page were to the archived version (https://github.com/ionic-team/vscode-extension/issues), they are replaced with the active version (https://github.com/ionic-team/vscode-ionic/issues)
=> replaced link to archived vs code extension issues page to current one

package-lock.json, package.json, src/theme/TOC/index.tsx
This PR:
- updates ionic preset to latest
- removes docusaurus deps that have been abstracted to preset
- updates useDoc file path that has been change in Docusaurus 3.5
=> chore: support docusaurus 3.5

docs/main/updating/7-0.md, sidebars.js
preview: https://capacitor-docs-git-rdmr-445-ionic1.vercel.app/docs/next/updating/7-0
=> docs: Add Updating to Capacitor 7 page

docs/main/android/index.md, docs/main/getting-started/environment-setup.md, docs/main/ios/index.md, docs/main/reference/support-policy.mdx
Update support page to include information about Capacitor 7.
Edit iOS/android/requirements pages to update information about supported SDKs and IDEs required versions.
=> docs: Update Capacitor 7 supported SDK/IDE versions

docs/main/ios/troubleshooting.md, versioned_docs/version-v2/android/configuration.md, versioned_docs/version-v2/android/troubleshooting.md, versioned_docs/version-v3/main/android/troubleshooting.md, versioned_docs/version-v3/main/ios/troubleshooting.md, versioned_docs/version-v3/main/ios/viewcontroller.md, versioned_docs/version-v3/main/updating/3-0.md, versioned_docs/version-v4/main/android/troubleshooting.md, versioned_docs/version-v4/main/ios/troubleshooting.md, versioned_docs/version-v4/main/ios/viewcontroller.md, versioned_docs/version-v4/main/updating/3-0.md, versioned_docs/version-v5/main/android/troubleshooting.md, versioned_docs/version-v5/main/ios/troubleshooting.md, versioned_docs/version-v5/main/ios/viewcontroller.md, versioned_docs/version-v5/main/updating/3-0.md, versioned_docs/version-v6/main/android/troubleshooting.md, versioned_docs/version-v6/main/ios/troubleshooting.md, versioned_docs/version-v6/main/ios/viewcontroller.md, versioned_docs/version-v6/main/updating/3-0.md
There are several links to Capacitor repository to main branch, since that could change at any moment, I've replaced the links on the versioned docs to point to the branch of the version they are for.
Also fixed a broken link to the ios template on main since it was renamed.
=> chore: use versioned github links

docusaurus.config.js, vercel.json
This PR:
- makes v7 the current version
- adds a redirect for all `/next` pages to current
=> chore(versions): make v7 current

versioned_docs/version-v2/android/updating.md, versioned_docs/version-v2/ios/configuration.md, versioned_docs/version-v2/ios/updating.md
make v2 docs links point to 2.x branch instead of master, which doesn't exists and despite github redirects, there were some renaming on iOS template
closes https://github.com/ionic-team/capacitor-docs/pull/373
=> docs: point template master branch links to 2.x

docs/main/ios/privacy-manifest.md, versioned_docs/version-v4/main/ios/privacy-manifest.md, versioned_docs/version-v5/main/ios/privacy-manifest.md, versioned_docs/version-v6/main/ios/privacy-manifest.md
closes https://github.com/ionic-team/capacitor-docs/pull/374
=> docs: fix typo in privacy manifest file

docs/apis/geolocation.md, scripts/api.mjs
The geolocation plugin is being migrated to https://github.com/ionic-team/capacitor-geolocation.
A new version will be released in the future - 7.1.0. Once it is stable (in `latest` channel), this PR can be updated with the latest docs and merged.
=> docs: geolocation plugin 7.1.0

docs/plugins/creating-plugins/ios-guide.md, versioned_docs/version-v6/plugins/creating-plugins/ios-guide.md
closes https://github.com/ionic-team/capacitor-docs/issues/49
=> docs: Add dependency examples on iOS plugin guide

docs/main/reference/support-policy.mdx
Added Maintenance and Extended Maintenance dates. Updated that Enterprise support is no longer being offered to new customers
=> docs(support-policy): Update Maintenance timeline

docs/plugins/tutorial/designing-api.md, docs/plugins/tutorial/implementing-for-android.md, docs/plugins/tutorial/implementing-for-ios.md, docs/plugins/tutorial/implementing-for-web.md
Most of the changes center around making sure the workflow lines up between sections and that the code matches what is required for current versions of Capacitor as the original tutorial was rather old.
=> docs: update the plugin tutorial

docs/apis/google-maps.md
The google-maps had a recently release, that also updated some docs that were missing in the doc page. This PR updates those missing docs.
=> docs: Update google-maps plugin
