ionic-team/capacitor-docs

- docs/main/reference/config.md
Bring latest changes from https://github.com/ionic-team/capacitor/blob/main/cli/src/declarations.ts
> chore: Update CapacitorConfig with latest changes

- docs/main/guides/autofill-credentials.md
> docs(autofill-credentials): fix apple-app-site-association

- docs/main/reference/config.md
add the information from https://github.com/ionic-team/capacitor/pull/5924
> docs(config): Sync with CLI declarations file

- README.md
Links for contributing and Contributor Code of Conduct were broken
> Fix broken Links in README.md

- docs/main/ios/custom-code.md
the diff-typescript doesn't work
> fix: use diff instead of diff-typescript on custom-code.md

- docs/apis/cookies.md
Fixed xml formatting for the WKAppBoundDomains example
> fix: info.plist formatting in cookies.md

- docs/main/getting-started/faqs.md
- docs/main/ios/troubleshooting.md
- versioned_docs/version-v3/main/ios/troubleshooting.md
closes https://github.com/ionic-team/capacitor-docs/issues/80
> docs: update troubleshooting and faqs with CocoaPods on Silicon

- docs/main/guides/push-notifications-firebase.md
Updated `Podfile`'s content to match the default `Podfile` generated by Capacitor v4.
> docs: update Podfile in push-notifications-firebase.md

- docs/main/getting-started/environment-setup.md
maybe it was intended like this, but autism made be rage at this lmao
> docs: correct number of items listed in environment setup 

- docs/main/guides/autofill-credentials.md
closes https://github.com/ionic-team/capacitor-docs/issues/73
> docs: clarify autofill guide for Android

- docs/apis/action-sheet.md
- docs/apis/browser.md
- docs/apis/camera.md
- docs/apis/geolocation.md
- docs/apis/google-maps.md
- docs/apis/local-notifications.md
- docs/apis/push-notifications.md
- docs/apis/screen-orientation.md
- docs/apis/splash-screen.md
- docs/apis/status-bar.md
- package.json
- scripts/api-v4.mjs
- versioned_docs/version-v4/apis/screen-orientation.md
create plugins script for v4 docs and run it
update plugin script to get latest v5 docs and run it
add screen-orientation plugin to both scripts so its docs get generated
> chore: generate capacitor 5 plugin docs

- docs/index.md
- docs/main/getting-started/environment-setup.md
- docs/main/updating/4-0.md
- docs/main/web/pwa-elements.md
- docs/plugins.md
Update environment setup with new Android Studio requirement and latest stable Android SDK
Update v4 links to v5 in main docs
> docs: More Capacitor 5 changes

- docs/main/vs-code-ext/3-build-and-run.md
- docs/main/vs-code-ext/4-debugging.md
- docs/main/vs-code-ext/monorepos.md
- docs/main/vs-code-ext/native-settings.md
- docs/main/vs-code-ext/z-advanced.md
Updates based on changes in v1.36 - 1.41 of the VS Code extension.
> docs(vscode): add keyboard shortcuts, update remote logging

- docs/main/reference/config.md
add `webContentsDebuggingEnabled` for iOS
> docs: Update config with Capacitor 5 definitions

- docs/main/android/index.md
- versioned_docs/version-v2/getting-started/dependencies.md
- versioned_docs/version-v3/main/android/index.md
- versioned_docs/version-v4/main/android/index.md
closes https://github.com/ionic-team/capacitor-docs/issues/42
update the Android docs for accuracy of Chrome/WebView usage
> Fix Android Webview/Chrome usage details

- docusaurus.config.js
The PR updates the blog link in the header.
> chore(config): blog link

- docs/main/reference/support-policy.md
we are in August 2023, so v3 is out of support now
> docs: Update support-policy.md

- docs/main/updating/5-0.md
closes https://github.com/ionic-team/capacitor-docs/issues/216
> docs(updating): Add note on jetifier removal

- docs/main/updating/5-0.md
Currently, the update section does not specify where to make this change.  The other changes in this document specify which files to change, so this item should, too.
> Add link to the configuration file

- docs/main/reference/support-policy.md
- versioned_docs/version-v5/main/reference/support-policy.md
Capacitor 4 has entered into Extended Support phase
> chore: Update support policy with Capacitor 4 change

- docs/main/reference/config.md
copy declarations file into the example
> chore: Update Capacitor config page for next

- docs/main/updating/6-0.md
Some information was incorrect, some was out of date, some was missing.
> chore: Update upgrade guide

- docusaurus.config.js
This PR changes the config to warn on broken anchors instead of throw an error.
> chore(config): throw -> warn on anchors

- docs/main/updating/6-0.md
google services plugin change was missing
and gradle plugin was updated to 8.2.1 recently
> chore: Add missing step on upgrade guide

- vercel.json
This reverts commit 91b0b3b52dd74a31aadbfeda6e3f3a06f3865218.
> Revert "Revert next directory redirects (#248)"

- docs/main/updating/plugins/6-0.md
> docs: fix typo un capacitor 6 upgrade guide

- docusaurus.config.js
- package.json
- src/styles/custom.scss
This PR:
- bumps Ionic Docs Theme to latest
- add an OS announcement bar to config and styles
> feat(): os announcement bar

- docs/apis/inappbrowser.md
- docs/plugins/official.md
- scripts/api.mjs
This PR adds the page for the `InAppBrowser` plugin documentation
> docs: add page for in app browser plugin

- docs/apis/google-maps.md
- Adds `getMapsBounds()` to documentation of `@capacitor/google-maps`
> chore: Generate plugin docs

- .npmrc
- package-lock.json
- package.json
This PR:
- adds back package-lock
- adds @docusaurus/theme-classic dep
- pins docusaurus deps and ionic preset to exact versions
> fix(deps): pinned docusaurus deps, package-lock

- docs/main/guides/push-notifications-firebase.md
Closing **}** was missing for  class **HomePage** in section https://capacitorjs.com/docs/guides/push-notifications-firebase#using-the-capacitor-push-notification-api
> Add closing } for the class HomePage in example snippet

- docs/main/web/pwa-elements.mdx
- versioned_docs/version-v3/main/web/pwa-elements.mdx
- versioned_docs/version-v4/main/web/pwa-elements.mdx
- versioned_docs/version-v5/main/web/pwa-elements.mdx
- versioned_docs/version-v6/main/web/pwa-elements.mdx
closes https://github.com/ionic-team/capacitor-docs/issues/357
> docs(pwa-elements): fix image

- docs/main/guides/environment-specific-configurations.md
- docs/main/web/index.md
bundledWebRuntime was removed, so no more script include docs.
> docs: remove bundledWebRuntime docs

- docs/main/ios/spm.md
- versioned_docs/version-v6/main/ios/spm.md
closes https://github.com/ionic-team/capacitor-docs/pull/378
closes https://github.com/ionic-team/capacitor-docs/pull/372
> docs: fix typos in spm docs
